<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Student [
<!ELEMENT Student (name?, age, marks, fees, class)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT marks (#PCDATA)>
<!ELEMENT fees (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT standard (#PCDATA)>
]>


<Student>
    <name>Ali</name>
    <age>39</age>
    <marks>100</marks>
    <fees>5000</fees>
    <class>9th</class>
</Student>